import { Container, Row, Col, Stack, Form, ListGroup, ListGroupItem } from 'react-bootstrap'
import { FaSearch } from 'react-icons/fa'
import TopBlogs from '@/components/TopBlogs';
import Hyperlink from '@/components/Hyperlink';

export const metadata = {
  title: "Blog detail",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Container className="mt-2">
      <Row>
        <Col xs={3} md={3}>
          <Stack gap={4}>
            <div>
              <Form className="d-flex align-items-center">
                <Form.Control size="sm" placeholder="search..." />
                <FaSearch size={14} className="text-secondary" style={{ marginLeft: '-22px' }} />
              </Form>
            </div>
            <div>
              <h6>Categories</h6>
              <ListGroup>
                <ListGroupItem active role="button">Culture</ListGroupItem>
                <ListGroupItem role="button">Creativity</ListGroupItem>
                <ListGroupItem role="button">Food</ListGroupItem>
                <ListGroupItem role="button">Travel</ListGroupItem>
                <ListGroupItem role="button">Music</ListGroupItem>
              </ListGroup>
            </div>
            <div className="p-3 bg-light-gray rounded">
              <h6>Top Blogs</h6>
              <div className="d-flex mb-2">
                <h2 className="fw-bolder me-2">1</h2>
                <div className="d-flex flex-column">
                  <span className="fw-bolder">Exercitation dolore veniam et aliqua.</span>
                  <span className="text-secondary fst-italic">Dolor ad ea incididunt elit velit nisi deserunt et esse esse sit non duis.</span>
                </div>
              </div>
              <div className="d-flex mb-2">
                <h2 className="fw-bolder me-2">2</h2>
                <div className="d-flex flex-column">
                  <span className="fw-bolder">Exercitation dolore veniam et aliqua.</span>
                  <span className="text-secondary fst-italic">Dolor ad ea incididunt elit velit nisi deserunt et esse esse sit non duis.</span>
                </div>
              </div>
              <div className="d-flex mb-2">
                <h2 className="fw-bolder me-2">3</h2>
                <div className="d-flex flex-column">
                  <span className="fw-bolder">Exercitation dolore veniam et aliqua.</span>
                  <span className="text-secondary fst-italic">Dolor ad ea incididunt elit velit nisi deserunt et esse esse sit non duis.</span>
                </div>
              </div>
            </div>
          </Stack>
        </Col>
        <Col xs={7} md={7}>
          {children}
        </Col>
        <Col xs={2} md={2}>
          <Stack gap={4}>
              <TopBlogs/>
              <Hyperlink/>
          </Stack>
        </Col>
      </Row>
    </Container>
  )
}
