import { Container, Row, Col, Stack, Form, ListGroup, ListGroupItem } from 'react-bootstrap'
import { FaSearch } from 'react-icons/fa'
import RecentArticles from '@/components/RecentArticles';
import Hyperlink from '@/components/Hyperlink';
import TopBlogs from '@/components/TopBlogs';
import Category from '@/components/Category';

export const metadata = {
  title: "Blog detail",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Container className="mt-2">
      <Row>
        <Col xs={3} md={3}>
          <Stack gap={4}>
            <div>
              <Form className="d-flex align-items-center">
                <Form.Control size="sm" placeholder="search..." />
                <FaSearch size={14} className="text-secondary" style={{ marginLeft: '-22px' }} />
              </Form>
            </div>
            <Category />
            <TopBlogs />
          </Stack>
        </Col>
        <Col xs={7} md={7}>
          {children}
        </Col>
        <Col xs={2} md={2}>
          <Stack gap={4}>
            <RecentArticles />
            <Hyperlink />
          </Stack>
        </Col>
      </Row>
    </Container>
  )
}
