import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import Footer from '@/components/Footer'
import { ToastContainer } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='container py-1 vh-100'>
          {children}
        </div>
        <Footer/>
        <ToastContainer/>
      </body>
    </html>
  )
}
