import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import Footer from '@/components/Footer'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Container } from 'react-bootstrap'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Khoa's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Container className='mb-5'>
          {children}
        </Container>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  )
}
